apiVersion: security.kubearmor.com/v1
kind: KubeArmorPolicy
metadata:
  name: wisecow-zero-trust
  namespace: wisecow
spec:
  selector:
    matchLabels:
      app: wisecow
  file:
    matchDirectories:
    - dir: /app/             # fixed
      recursive: true
    - dir: /var/log/wisecow/ # fixed
      recursive: true
    - dir: /etc/wisecow/     # fixed
      recursive: true
  process:
    matchPaths:
    - path: /usr/local/bin/wisecow
  action:
    Allow
