name: ci-cd-wisecow

on:
  push:
    branches: ["main"]

jobs:
  build-push-deploy:
    runs-on: ubuntu-latest   

    permissions:
      contents: read
      packages: write

    steps:
      # Checkout repo
      - name: Checkout repository
        uses: actions/checkout@v4

      # Setup kind cluster
      - name: Setup kind cluster
        uses: helm/kind-action@v1.8.0
        with:
          cluster_name: kind
          version: v0.30.0
          config: ./kind-config.yaml

      # Log in to GHCR
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GH_TOKEN }}

      # Build & Push Docker image
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/wisecow:v1

      # Install cert-manager
      - name: Setup cert-manager
        run: |
          kubectl apply -f https://github.com/cert-manager/cert-manager/releases/download/v1.14.4/cert-manager.yaml
          kubectl wait --for=condition=Available --timeout=300s deployment -n cert-manager --all
      
      # Nginx Installation
      - name: Install ingress-nginx without admission webhook
        run: |
          helm repo add ingress-nginx https://kubernetes.github.io/ingress-nginx
          helm repo update
          helm install ingress-nginx ingress-nginx/ingress-nginx \
            --namespace ingress-nginx --create-namespace \
            --set controller.admissionWebhooks.enabled=false


      # Load image into kind
      - name: Load image into kind
        run: |
          
          kind load docker-image ghcr.io/${{ github.repository_owner }}/wisecow:v1 --name kind

      # Create namespace
      - name: Create namespace
        run: kubectl create namespace wisecow || true
      
      # TLS secret
      - name: Create TLS secret
        run: |
          openssl req -x509 -nodes -days 365 -newkey rsa:2048 \
          -out tls.crt -keyout tls.key \
          -subj "/CN=wisecow.127.0.0.1.nip.io/O=wisecow"

          kubectl create secret tls wisecow-tls \
          --cert=tls.crt --key=tls.key -n wisecow

      # Deploy manifests
      - name: Deploy manifests
        run: |
          kubectl apply -f k8s/deploy.yaml -n wisecow
          kubectl apply -f k8s/clusterissuer.yaml -n wisecow
          kubectl apply -f k8s/ingress.yaml -n wisecow
          kubectl apply -f k8s/service.yaml -n wisecow
 